; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
build_cache_dir = .pio/cache

[env:nucleo_f446re]
; 上3つは，PlatformIOでnew projectしたときのものをコピペします
platform = ststm32
board = nucleo_f446re
framework = stm32cube
; コンパイルされるフォルダです
; Srcにmain.cがあるので，Srcを指定しなければmain関数が見つからなくなってしまいます
; Inc内にライブラリを入れた場合，そのソースはInc内にあることになるため，Incも指定します
build_src_filter = 
    +<../Core/Src>
    +<../Core/Inc>
; includeするときに探しに行くところです
; Incを指定します
build_flags =
    -ICore/Inc
